name: pokemon_price
version: 0.1.0
config-version: 2

profile: pokemon_price

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  landing_dir: "../landing"

models:
  pokemon_price:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

seeds:
  pokemon_price:
    set_release_date_overrides:
      +column_types:
        set_id: integer
        set_release_date: date
        is_cohort_eligible: boolean
        set_name: varchar
        notes: varchar
        source_url: varchar
