name: pokemon_price
version: 0.1.0
config-version: 2

profile: pokemon_price

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  landing_dir: "../landing"

models:
  pokemon_price:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
